### ISSUE TITLE
Performance comparison to baseline models

### ISSUE THREAD

**Issue by bkj** [EdGENetworks/attention-networks-for-classification#1]
I was wondering whether you could add accuracy numbers to the notebook/README rather than just the loss numbers.  Also, do you know the accuracy/loss values for a baseline network?  Does the HAN outperform?

Thanks!

**Comment by Sandeep42** [comment]
I am still experimenting with the model, and I did manage to include the bias term that was missing, I probably won't have time to cross-validate all their results, but I will do that on one data set and update here very soon. Please feel free to report any testings that you might have done!
