### ISSUE TITLE
Sentence model bug when GRU are not bidirectional

### ISSUE THREAD

**Issue by gabrer** [EdGENetworks/attention-networks-for-classification#12]
A small bug does not allow to train the network when _Bidirectional_ is set to _False_.

In "model.py", on line 135, _Bidirectional_ should be set to "_False_": [Line 135](https://github.com/EdGENetworks/attention-networks-for-classification/blob/9c77a876e6028d8255cdcad3a6c1ff5273cb9f84/model.py#L135)

From:
`            self.sent_gru = nn.GRU(word_gru_hidden, sent_gru_hidden, bidirectional= True)        `
to:
`            self.sent_gru = nn.GRU(word_gru_hidden, sent_gru_hidden, bidirectional= False)        `

**Comment by Sandeep42** [comment]
Thanks for finding this out, I have updated the code to reflect this change.
