### ISSUE TITLE
imdb_final.json

### ISSUE THREAD

**Issue by hycis** [EdGENetworks/attention-networks-for-classification#2]
could you share with me the imdb_final.json file you are using

**Comment by hycis** [comment]
do you have a script to parse for example a dataframe of colums = ['text', 'label'] into the format i can train with your model?

**Comment by Sandeep42** [comment]
Here is it.
https://drive.google.com/file/d/0B1RmSd_tWx4CUnFQaXdvV2R1NFk/view?usp=sharing
