### ISSUE TITLE
An example for save this model

### ISSUE THREAD

**Issue by lawlietAi** [EdGENetworks/attention-networks-for-classification#4]
thanks for your code. i've got an 40% acc in my work.but when i attempt to save this model, i'm confused. plz help me and give me an example for save this model. 
thank you!

**Comment by Sandeep42** [comment]
You can save individual Word and Sentence encoders separately.
`torch.save(model_name.state_dict(), model_path) `
When loading, you can use torch.load function the saved model file into memory, and use
`model.load_state_dict()`

**Comment by lawlietAi** [comment]
thanks for your explaination.great work
