### ISSUE TITLE
single data prediction

### ISSUE THREAD

**Issue by lawlietAi** [EdGENetworks/attention-networks-for-classification#5]
I'm new in python. In your model,hidden state depend on the batch_size.when i want a single data prediction i've got problems.could you help me or give me some code?

**Comment by Sandeep42** [comment]
You can load both models and set batch size to 1. After that you can do something like this. Hope that helps.
`def get_predictions_single(val_tokens, word_attn_model, sent_attn_model):
    state_word = word_attn_model.init_hidden().cuda()
    state_sent = sent_attn_model.init_hidden().cuda()
    s = None
    word_attns = []
    for sent in val_tokens:
        sent = Variable(torch.from_numpy(np.array(sent)).unsqueeze(0).transpose(0,1), requires_grad= False, volatile = True).cuda()
        print sent.size()
        print state_word.size()
        _s, state_word, _ = word_attn_model(sent, state_word)
        if(s is None):
            s = _s
        else:
            s = torch.cat((s,_s),0)
        word_attns.append(word_attns_)
    y_pred, state_sent, sent_attns = sent_attn_model(s, state_sent)    
    return y_pred, word_attns, sent_attns`
